// GENERADO por scripts/gen-schemas.mjs desde _source/cms/commercials.csv
// Colección de Webflow: commercials (3 items) · sin página propia (solo datos)
import { defineType } from 'sanity'

export default defineType({
  name: 'commercialService',
  title: 'Servicio comercial',
  type: 'document',
  fields: [
    {
      name: 'name',
      title: 'Nombre',
      type: 'string',
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'faqs',
      title: 'Faqs',
      description: 'Plegado desde 5 grupos de columnas de Webflow',
      type: 'array',
      of: [{
        type: 'object',
        fields: [
        { name: 'question', title: 'Question', type: 'text', rows: 3 },
        { name: 'answer', title: 'Answer', type: 'text', rows: 3 },
        ],
      }],
    },
    {
      name: 'features',
      title: 'Features',
      description: 'Plegado desde 6 grupos de columnas de Webflow',
      type: 'array',
      of: [{
        type: 'object',
        fields: [
        { name: 'heading', title: 'Heading', type: 'text', rows: 3 },
        { name: 'body', title: 'Body', type: 'text', rows: 3 },
        { name: 'image', title: 'Image', type: 'image', options: { hotspot: true }, fields: [{ name: 'alt', type: 'string', title: 'Alt' }] },
        ],
      }],
    },
    {
      name: 'slug',
      title: 'Slug',
      description: 'Webflow: Slug',
      type: 'slug',
      options: { source: 'name', maxLength: 96 },
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'legacyId',
      title: 'Legacy Id',
      description: 'Webflow: Item ID',
      type: 'string',
    },
    {
      name: 'publishedAt',
      title: 'Published At',
      description: 'Webflow: Published On',
      type: 'datetime',
    },
    {
      name: 'categories',
      title: 'Categories',
      description: 'Webflow: Categories — vacía en el export',
      type: 'string',
    },
    {
      name: 'icon',
      title: 'Icon',
      description: 'Webflow: Icon',
      type: 'image',
      options: { hotspot: true },
      fields: [{ name: 'alt', type: 'string', title: 'Alt' }],
    },
    {
      name: 'iDClass',
      title: 'I D Class',
      description: 'Webflow: ID Class',
      type: 'string',
    },
    {
      name: 'imagePage',
      title: 'Image Page',
      description: 'Webflow: Image Page',
      type: 'image',
      options: { hotspot: true },
      fields: [{ name: 'alt', type: 'string', title: 'Alt', description: 'Webflow: Metadata Image Page' }],
    },
    {
      name: 'titleService',
      title: 'Title Service',
      description: 'Webflow: Title Service',
      type: 'string',
    },
    {
      name: 'summary',
      title: 'Summary',
      description: 'Webflow: Summary',
      type: 'string',
    },
    {
      name: 'headingIntro',
      title: 'Heading Intro',
      description: 'Webflow: Heading Intro',
      type: 'string',
    },
    {
      name: 'paragraphIntro',
      title: 'Paragraph Intro',
      description: 'Webflow: Paragraph Intro',
      type: 'string',
    },
    {
      name: 'imageAnimation1',
      title: 'Image Animation1',
      description: 'Webflow: Image Animation 1',
      type: 'image',
      options: { hotspot: true },
      fields: [{ name: 'alt', type: 'string', title: 'Alt', description: 'Webflow: Metadata Image Animation 1' }],
    },
    {
      name: 'imageAnimation2',
      title: 'Image Animation2',
      description: 'Webflow: Image Animation 2',
      type: 'image',
      options: { hotspot: true },
      fields: [{ name: 'alt', type: 'string', title: 'Alt', description: 'Webflow: Metadata Image Animation 2' }],
    },
    {
      name: 'imageAnimation3',
      title: 'Image Animation3',
      description: 'Webflow: Image Animation 3',
      type: 'image',
      options: { hotspot: true },
      fields: [{ name: 'alt', type: 'string', title: 'Alt', description: 'Webflow: Metadata Image Animation 3' }],
    },
    {
      name: 'headingServices',
      title: 'Heading Services',
      description: 'Webflow: Heading Services',
      type: 'string',
    },
    {
      name: 'paragraphServices',
      title: 'Paragraph Services',
      description: 'Webflow: Paragraph Services',
      type: 'string',
    },
    {
      name: 'headingFeature',
      title: 'Heading Feature',
      description: 'Webflow: Heading Feature',
      type: 'string',
    },
    {
      name: 'paragraphFeature',
      title: 'Paragraph Feature',
      description: 'Webflow: Paragraph Feature',
      type: 'string',
    },
    {
      name: 'sEOMetadataImageFeature1',
      title: 'S E O Metadata Image Feature1',
      description: 'Webflow: SEO Metadata Image Feature 1',
      type: 'string',
    },
    {
      name: 'sEOMetadataImageFeature3',
      title: 'S E O Metadata Image Feature3',
      description: 'Webflow: SEO Metadata Image Feature 3',
      type: 'string',
    },
    {
      name: 'sEOMetadataImageFeature2',
      title: 'S E O Metadata Image Feature2',
      description: 'Webflow: SEO Metadata Image Feature 2',
      type: 'string',
    },
    {
      name: 'sEOMetadataImageFeature4',
      title: 'S E O Metadata Image Feature4',
      description: 'Webflow: SEO Metadata Image Feature 4',
      type: 'string',
    },
    {
      name: 'sEOMetadataImageFeature5',
      title: 'S E O Metadata Image Feature5',
      description: 'Webflow: SEO Metadata Image Feature 5',
      type: 'string',
    },
    {
      name: 'sEOMetadataImageFeature6',
      title: 'S E O Metadata Image Feature6',
      description: 'Webflow: SEO Metadata Image Feature 6',
      type: 'string',
    },
    {
      name: 'paragraphGallery',
      title: 'Paragraph Gallery',
      description: 'Webflow: Paragraph Gallery',
      type: 'string',
    },
    {
      name: 'paragraphProcess',
      title: 'Paragraph Process',
      description: 'Webflow: Paragraph Process',
      type: 'string',
    },
    {
      name: 'paragraphBrochure',
      title: 'Paragraph Brochure',
      description: 'Webflow: Paragraph Brochure',
      type: 'string',
    },
    {
      name: 'paragraphProjects',
      title: 'Paragraph Projects',
      description: 'Webflow: Paragraph Projects',
      type: 'string',
    },
    {
      name: 'paragraphReview',
      title: 'Paragraph Review',
      description: 'Webflow: Paragraph Review',
      type: 'string',
    },
    {
      name: 'seo',
      title: 'SEO',
      type: 'seo',
      description: 'Webflow: Title SEO / Description SEO',
    },
  ],
  preview: { select: { title: 'name', subtitle: 'slug.current' } },
})
