// GENERADO por scripts/gen-schemas.mjs desde _source/cms/countries.csv
// Colección de Webflow: countries (9 items) · página propia: /country/{slug}
import { defineType } from 'sanity'

export default defineType({
  name: 'county',
  title: 'Condado',
  type: 'document',
  fields: [
    {
      name: 'name',
      title: 'Nombre',
      type: 'string',
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'slug',
      title: 'Slug',
      description: 'Webflow: Slug',
      type: 'slug',
      options: { source: 'name', maxLength: 96 },
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'legacyId',
      title: 'Legacy Id',
      description: 'Webflow: Item ID',
      type: 'string',
    },
    {
      name: 'publishedAt',
      title: 'Published At',
      description: 'Webflow: Published On',
      type: 'datetime',
    },
    {
      name: 'region',
      title: 'Region',
      description: 'Webflow: Region',
      type: 'reference',
      to: [{ type: 'serviceRegion' }],
    },
    {
      name: 'mainImage',
      title: 'Main Image',
      description: 'Webflow: Main Image',
      type: 'image',
      options: { hotspot: true },
      fields: [{ name: 'alt', type: 'string', title: 'Alt', description: 'Webflow: Metadescription Main Image SEO' }],
    },
    {
      name: 'headingPage',
      title: 'Heading Page',
      description: 'Webflow: Heading Page',
      type: 'string',
    },
    {
      name: 'summaryIntroPage',
      title: 'Summary Intro Page',
      description: 'Webflow: Summary Intro Page',
      type: 'string',
    },
    {
      name: 'headingIntro',
      title: 'Heading Intro',
      description: 'Webflow: Heading Intro',
      type: 'string',
    },
    {
      name: 'paragraphIntro',
      title: 'Paragraph Intro',
      description: 'Webflow: Paragraph Intro',
      type: 'string',
    },
    {
      name: 'imagenIntro1',
      title: 'Imagen Intro1',
      description: 'Webflow: Imagen Intro 1',
      type: 'image',
      options: { hotspot: true },
      fields: [{ name: 'alt', type: 'string', title: 'Alt', description: 'Webflow: Metadata Imagen Intro 1' }],
    },
    {
      name: 'imagenIntro2',
      title: 'Imagen Intro2',
      description: 'Webflow: Imagen Intro 2',
      type: 'image',
      options: { hotspot: true },
      fields: [{ name: 'alt', type: 'string', title: 'Alt', description: 'Webflow: Metadata Imagen Intro 2' }],
    },
    {
      name: 'imagenIntro3',
      title: 'Imagen Intro3',
      description: 'Webflow: Imagen Intro 3',
      type: 'image',
      options: { hotspot: true },
      fields: [{ name: 'alt', type: 'string', title: 'Alt', description: 'Webflow: Metadata Imagen Intro 3' }],
    },
    {
      name: 'heading3DRendeingDesign',
      title: 'Heading3 D Rendeing Design',
      description: 'Webflow: Heading 3D Rendeing Design',
      type: 'string',
    },
    {
      name: 'text3DRendeingDesign',
      title: 'Text3 D Rendeing Design',
      description: 'Webflow: Text 3D Rendeing Design',
      type: 'string',
    },
    {
      name: 'headingGallery',
      title: 'Heading Gallery',
      description: 'Webflow: Heading Gallery',
      type: 'string',
    },
    {
      name: 'textGallery',
      title: 'Text Gallery',
      description: 'Webflow: Text Gallery',
      type: 'string',
    },
    {
      name: 'headingProject',
      title: 'Heading Project',
      description: 'Webflow: Heading Project',
      type: 'string',
    },
    {
      name: 'textProject',
      title: 'Text Project',
      description: 'Webflow: Text Project',
      type: 'string',
    },
    {
      name: 'headingReviews',
      title: 'Heading Reviews',
      description: 'Webflow: Heading Reviews',
      type: 'string',
    },
    {
      name: 'textReviews',
      title: 'Text Reviews',
      description: 'Webflow: Text Reviews',
      type: 'string',
    },
    {
      name: 'headingBlog',
      title: 'Heading Blog',
      description: 'Webflow: Heading Blog',
      type: 'string',
    },
    {
      name: 'textBlog',
      title: 'Text Blog',
      description: 'Webflow: Text Blog',
      type: 'string',
    },
    {
      name: 'seo',
      title: 'SEO',
      type: 'seo',
      description: 'Webflow: Title SEO / Metadescription SEO',
    },
  ],
  preview: { select: { title: 'name', subtitle: 'slug.current' } },
})
