// GENERADO por scripts/gen-schemas.mjs
import seo from './seo'
import service from './service'
import commercialService from './commercialService'
import poolBuilder from './poolBuilder'
import county from './county'
import serviceRegion from './serviceRegion'
import project from './project'
import blogPost from './blogPost'
import article from './article'
import subservice from './subservice'
import processStep from './processStep'
import galleryImage from './galleryImage'
import brochure from './brochure'
import brochureCategory from './brochureCategory'
import category from './category'
import industry from './industry'
import logo from './logo'

export const schemaTypes = [seo, service, commercialService, poolBuilder, county, serviceRegion, project, blogPost, article, subservice, processStep, galleryImage, brochure, brochureCategory, category, industry, logo]
