// GENERADO por scripts/gen-schemas.mjs desde _source/cms/pool-builders.csv
// Colección de Webflow: pool-builders (53 items) · página propia: /pool-builders/{slug}
import { defineType } from 'sanity'

export default defineType({
  name: 'poolBuilder',
  title: 'Pool Builder (ciudad)',
  type: 'document',
  fields: [
    {
      name: 'name',
      title: 'Nombre',
      type: 'string',
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'slug',
      title: 'Slug',
      description: 'Webflow: Slug',
      type: 'slug',
      options: { source: 'name', maxLength: 96 },
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'legacyId',
      title: 'Legacy Id',
      description: 'Webflow: Item ID',
      type: 'string',
    },
    {
      name: 'publishedAt',
      title: 'Published At',
      description: 'Webflow: Published On',
      type: 'datetime',
    },
    {
      name: 'country',
      title: 'Country',
      description: 'Webflow: Country',
      type: 'reference',
      to: [{ type: 'county' }],
    },
    {
      name: 'h1Title',
      title: 'H1 Title',
      description: 'Webflow: H1 Title',
      type: 'string',
    },
    {
      name: 'h2Title',
      title: 'H2 Title',
      description: 'Webflow: H2 Title',
      type: 'string',
    },
    {
      name: 'intro',
      title: 'Intro',
      description: 'Webflow: Intro',
      type: 'string',
    },
    {
      name: 'headingIntro',
      title: 'Heading Intro',
      description: 'Webflow: Heading Intro',
      type: 'string',
    },
    {
      name: 'paragraphIntro',
      title: 'Paragraph Intro',
      description: 'Webflow: Paragraph Intro',
      type: 'text',
      rows: 4,
    },
    {
      name: 'imagenIntro1',
      title: 'Imagen Intro1',
      description: 'Webflow: Imagen Intro 1',
      type: 'image',
      options: { hotspot: true },
      fields: [{ name: 'alt', type: 'string', title: 'Alt', description: 'Webflow: Metadata Imagen Intro 1' }],
    },
    {
      name: 'imagenIntro2',
      title: 'Imagen Intro2',
      description: 'Webflow: Imagen Intro 2',
      type: 'image',
      options: { hotspot: true },
      fields: [{ name: 'alt', type: 'string', title: 'Alt', description: 'Webflow: Metadata Imagen Intro 2' }],
    },
    {
      name: 'imagenIntro3',
      title: 'Imagen Intro3',
      description: 'Webflow: Imagen Intro 3',
      type: 'image',
      options: { hotspot: true },
      fields: [{ name: 'alt', type: 'string', title: 'Alt', description: 'Webflow: Metadata Imagen Intro 3' }],
    },
    {
      name: 'heading3DRendering',
      title: 'Heading3 D Rendering',
      description: 'Webflow: Heading 3D Rendering',
      type: 'string',
    },
    {
      name: 'paragraph3DRendering',
      title: 'Paragraph3 D Rendering',
      description: 'Webflow: Paragraph 3D Rendering',
      type: 'string',
    },
    {
      name: 'headingFeature',
      title: 'Heading Feature',
      description: 'Webflow: Heading Feature',
      type: 'string',
    },
    {
      name: 'paragraphFeatures',
      title: 'Paragraph Features',
      description: 'Webflow: Paragraph Features',
      type: 'string',
    },
    {
      name: 'headingPortfolio',
      title: 'Heading Portfolio',
      description: 'Webflow: Heading Portfolio',
      type: 'string',
    },
    {
      name: 'paragraphPortfolio',
      title: 'Paragraph Portfolio',
      description: 'Webflow: Paragraph Portfolio',
      type: 'string',
    },
    {
      name: 'headingReviews',
      title: 'Heading Reviews',
      description: 'Webflow: Heading Reviews',
      type: 'string',
    },
    {
      name: 'paragraphReviews',
      title: 'Paragraph Reviews',
      description: 'Webflow: Paragraph Reviews',
      type: 'string',
    },
    {
      name: 'headingBlog',
      title: 'Heading Blog',
      description: 'Webflow: Heading Blog',
      type: 'string',
    },
    {
      name: 'paragraphBlog',
      title: 'Paragraph Blog',
      description: 'Webflow: Paragraph Blog',
      type: 'string',
    },
    {
      name: 'seo',
      title: 'SEO',
      type: 'seo',
      description: 'Webflow: Meta Title / Meta Description',
    },
  ],
  preview: { select: { title: 'name', subtitle: 'slug.current' } },
})
