// GENERADO por scripts/gen-schemas.mjs desde _source/cms/residentials.csv
// Colección de Webflow: residentials (14 items) · página propia: /services/{slug}
import { defineType } from 'sanity'

export default defineType({
  name: 'service',
  title: 'Servicio (residencial)',
  type: 'document',
  fields: [
    {
      name: 'name',
      title: 'Nombre',
      type: 'string',
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'faqs',
      title: 'Faqs',
      description: 'Plegado desde 5 grupos de columnas de Webflow',
      type: 'array',
      of: [{
        type: 'object',
        fields: [
        { name: 'question', title: 'Question', type: 'text', rows: 3 },
        { name: 'answer', title: 'Answer', type: 'text', rows: 3 },
        ],
      }],
    },
    {
      name: 'slug',
      title: 'Slug',
      description: 'Webflow: Slug',
      type: 'slug',
      options: { source: 'name', maxLength: 96 },
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'legacyId',
      title: 'Legacy Id',
      description: 'Webflow: Item ID',
      type: 'string',
    },
    {
      name: 'publishedAt',
      title: 'Published At',
      description: 'Webflow: Published On',
      type: 'datetime',
    },
    {
      name: 'feature',
      title: 'Feature',
      description: 'Webflow: Feature',
      type: 'boolean',
    },
    {
      name: 'categories',
      title: 'Categories',
      description: 'Webflow: Categories',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'category' }] }],
    },
    {
      name: 'icon',
      title: 'Icon',
      description: 'Webflow: Icon',
      type: 'image',
      options: { hotspot: true },
      fields: [{ name: 'alt', type: 'string', title: 'Alt' }],
    },
    {
      name: 'serviceID',
      title: 'Service I D',
      description: 'Webflow: Service ID',
      type: 'string',
    },
    {
      name: 'imagePage',
      title: 'Image Page',
      description: 'Webflow: Image Page',
      type: 'image',
      options: { hotspot: true },
      fields: [{ name: 'alt', type: 'string', title: 'Alt', description: 'Webflow: Metadata Image Page' }],
    },
    {
      name: 'titleService',
      title: 'Title Service',
      description: 'Webflow: Title Service',
      type: 'string',
    },
    {
      name: 'summary',
      title: 'Summary',
      description: 'Webflow: Summary',
      type: 'string',
    },
    {
      name: 'headingIntro',
      title: 'Heading Intro',
      description: 'Webflow: Heading Intro',
      type: 'string',
    },
    {
      name: 'paragraphIntro',
      title: 'Paragraph Intro',
      description: 'Webflow: Paragraph Intro',
      type: 'text',
      rows: 4,
    },
    {
      name: 'imageAnimation1',
      title: 'Image Animation1',
      description: 'Webflow: Image Animation 1',
      type: 'image',
      options: { hotspot: true },
      fields: [{ name: 'alt', type: 'string', title: 'Alt', description: 'Webflow: Metadata Image Animation 1' }],
    },
    {
      name: 'imageAnimation2',
      title: 'Image Animation2',
      description: 'Webflow: Image Animation 2',
      type: 'image',
      options: { hotspot: true },
      fields: [{ name: 'alt', type: 'string', title: 'Alt', description: 'Webflow: Metadata Image Animation 2' }],
    },
    {
      name: 'imageAnimation3',
      title: 'Image Animation3',
      description: 'Webflow: Image Animation 3',
      type: 'image',
      options: { hotspot: true },
      fields: [{ name: 'alt', type: 'string', title: 'Alt', description: 'Webflow: Metadata Image Animation 3' }],
    },
    {
      name: 'headingServices',
      title: 'Heading Services',
      description: 'Webflow: Heading Services',
      type: 'string',
    },
    {
      name: 'paragraphServices',
      title: 'Paragraph Services',
      description: 'Webflow: Paragraph Services',
      type: 'string',
    },
    {
      name: 'headingBeforeAfter',
      title: 'Heading Before After',
      description: 'Webflow: Heading Before & After',
      type: 'string',
    },
    {
      name: 'paragraphBeforeAfter',
      title: 'Paragraph Before After',
      description: 'Webflow: Paragraph Before & After',
      type: 'text',
      rows: 4,
    },
    {
      name: 'beforeImage',
      title: 'Before Image',
      description: 'Webflow: Before Image',
      type: 'image',
      options: { hotspot: true },
      fields: [{ name: 'alt', type: 'string', title: 'Alt', description: 'Webflow: Metadata Before Image' }],
    },
    {
      name: 'afterImage',
      title: 'After Image',
      description: 'Webflow: After Image',
      type: 'image',
      options: { hotspot: true },
      fields: [{ name: 'alt', type: 'string', title: 'Alt', description: 'Webflow: Metadata After Image' }],
    },
    {
      name: 'headingProcess',
      title: 'Heading Process',
      description: 'Webflow: Heading Process',
      type: 'string',
    },
    {
      name: 'paragraphProcess',
      title: 'Paragraph Process',
      description: 'Webflow: Paragraph Process',
      type: 'string',
    },
    {
      name: 'headingGallery',
      title: 'Heading Gallery',
      description: 'Webflow: Heading Gallery',
      type: 'string',
    },
    {
      name: 'paragraphGallery',
      title: 'Paragraph Gallery',
      description: 'Webflow: Paragraph Gallery',
      type: 'string',
    },
    {
      name: 'headingFAQ',
      title: 'Heading F A Q',
      description: 'Webflow: Heading FAQ',
      type: 'string',
    },
    {
      name: 'paragraphFAQ',
      title: 'Paragraph F A Q',
      description: 'Webflow: Paragraph FAQ',
      type: 'string',
    },
    {
      name: 'headingReviews',
      title: 'Heading Reviews',
      description: 'Webflow: Heading Reviews',
      type: 'string',
    },
    {
      name: 'paragraphReviews',
      title: 'Paragraph Reviews',
      description: 'Webflow: Paragraph Reviews',
      type: 'string',
    },
    {
      name: 'seo',
      title: 'SEO',
      type: 'seo',
      description: 'Webflow: Title SEO / Description SEO',
    },
  ],
  preview: { select: { title: 'name', subtitle: 'slug.current' } },
})
