#!/usr/bin/env node
/**
 * INFORME DE RED — que pesa una pagina y que parte de eso es critico (SEO-REMEDIACION, 4-oct-2026).
 *
 *     node scripts/informe-red.mjs <antes.json> <despues.json> <salida.md> [titulo]
 *
 * Lee dos informes JSON de Lighthouse (mismo ajuste, misma pagina) y escribe una tabla por recurso:
 * tipo, bytes transferidos, bytes decodificados, prioridad, si estaba en la cadena critica y en
 * que momento acabo. No mide nada por su cuenta: todo sale del audit `network-requests`, para que
 * el numero lleve detras el comando que lo produjo.
 */
import fs from 'node:fs';

const [antesF, despuesF, salida, titulo = 'Página'] = process.argv.slice(2);
if (!antesF || !despuesF || !salida) { console.error('uso: informe-red.mjs antes.json despues.json salida.md [titulo]'); process.exit(1); }

const lee = (f) => {
  const r = JSON.parse(fs.readFileSync(f, 'utf8'));
  const items = r.audits['network-requests'].details.items;
  const lcp = r.audits['largest-contentful-paint'].numericValue;
  const criticas = new Set();
  (function recorre(n) { for (const [, v] of Object.entries(n ?? {})) { if (v.request?.url) criticas.add(v.request.url); recorre(v.children); } })(
    r.audits['critical-request-chains']?.details?.chains);
  return { r, items, lcp, criticas, total: r.audits['total-byte-weight'].numericValue };
};
const A = lee(antesF);
const D = lee(despuesF);
const kb = (b) => (b / 1024).toFixed(1);
const corta = (u) => u.replace(/^https?:\/\/[^/]+/, '').slice(0, 90);
const uso = (u, t) => (/\/videos\//.test(u) ? 'background video'
  : /posters\//.test(u) ? 'video poster (LCP image)'
  : /\.woff2/.test(u) ? 'font'
  : /googletagmanager|gtag/.test(u) ? 'tag manager / ads (blocked in the lab container)'
  : t === 'Script' ? 'script' : t === 'Stylesheet' ? 'stylesheet' : t === 'Document' ? 'HTML' : t === 'Image' ? 'image' : t);

const fila = (x, criticas, lcp) => `| \`${corta(x.url)}\` | ${x.resourceType ?? ''} | ${kb(x.transferSize ?? 0)} | ${kb(x.resourceSize ?? 0)} | ${x.priority ?? ''} | ${criticas.has(x.url) ? 'yes' : (x.networkEndTime ?? 0) <= lcp ? 'before LCP' : 'no'} | ${uso(x.url, x.resourceType)} |`;
const tabla = (S) => S.items.filter((x) => (x.transferSize ?? 0) > 2048)
  .sort((a, b) => (b.transferSize ?? 0) - (a.transferSize ?? 0)).slice(0, 25)
  .map((x) => fila(x, S.criticas, S.lcp)).join('\n');
const porTipo = (S) => Object.entries(S.items.reduce((a, x) => ((a[x.resourceType ?? 'Other'] = (a[x.resourceType ?? 'Other'] ?? 0) + (x.transferSize ?? 0)), a), {}))
  .sort((a, b) => b[1] - a[1]);
const tiposA = Object.fromEntries(porTipo(A));
const tiposD = Object.fromEntries(porTipo(D));
const tipos = [...new Set([...Object.keys(tiposA), ...Object.keys(tiposD)])];

const md = `# Network asset report — ${titulo}

Generated by \`node scripts/informe-red.mjs\` from two Lighthouse 13 JSON reports (mobile, simulated
throttling, same local server over \`.vercel/output/static\`). Before = \`main\` @ \`2b800c7\`; after =
this branch. Third-party tags (GTM, Google Ads) are blocked by the lab container's proxy, so their
bytes are **not** included in either column; in production they add the same amount before and after.

| | Before | After |
|---|---|---|
| Total transferred | ${kb(A.total)} KB | ${kb(D.total)} KB |
| Requests | ${A.items.length} | ${D.items.length} |
| LCP (lab) | ${(A.lcp / 1000).toFixed(2)} s | ${(D.lcp / 1000).toFixed(2)} s |

## Transfer by resource type (KB)

| Type | Before | After |
|---|---|---|
${tipos.map((t) => `| ${t} | ${kb(tiposA[t] ?? 0)} | ${kb(tiposD[t] ?? 0)} |`).join('\n')}

## Largest resources — before

| Resource | Type | Transferred KB | Decoded KB | Priority | Critical / before LCP | Usage |
|---|---|---|---|---|---|---|
${tabla(A)}

## Largest resources — after

| Resource | Type | Transferred KB | Decoded KB | Priority | Critical / before LCP | Usage |
|---|---|---|---|---|---|---|
${tabla(D)}
`;
fs.writeFileSync(salida, md);
console.log(`informe de red: ${salida} · ${kb(A.total)} KB -> ${kb(D.total)} KB`);
